name: 'Build and Push CN Images'
description: 'Build and push CN (Chinese) versions of Docker images'
inputs:
  dockerfile:
    description: 'Dockerfile path'
    required: true
  ghcr_image_name:
    description: 'ghcr.io CN image name'
    required: true
  acr_image_name:
    description: 'Aliyun ACR CN image name'
    required: false
    default: ''
  aliyun_credentials:
    description: 'JSON object containing Aliyun ACR credentials { "registry": string, "username": string, "password": string }'
    required: false
    default: '{}'
runs:
  using: 'composite'
  steps:
    - name: Build and push CN image to ghcr.io
      shell: bash
      run: |
        echo "Building and pushing CN image to ghcr.io: ${{ inputs.ghcr_image_name }}"
        ./bin/runtimectl ci build "${{ inputs.dockerfile }}" "${{ inputs.ghcr_image_name }}" --cn --push | bash
    - name: Build and push CN image to Aliyun ACR
      shell: bash
      run: |
        # Check if Aliyun credentials are provided
        aliyun_credentials='${{ inputs.aliyun_credentials }}'
        if [ "$aliyun_credentials" != "{}" ] && [ "$aliyun_credentials" != "" ] && [ "$aliyun_credentials" != "null" ] && [ "${{ inputs.acr_image_name }}" != "" ]; then
          registry=$(echo "$aliyun_credentials" | jq -r '.registry')
          if [ -n "$registry" ] && [ "$registry" != "null" ]; then
            echo "Building and pushing CN image to Aliyun ACR: ${{ inputs.acr_image_name }}"
            ./bin/runtimectl ci build "${{ inputs.dockerfile }}" "${{ inputs.acr_image_name }}" --cn --push | bash
          fi
        fi
