apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: rust-1-81-0
  namespace: devbox-system
spec:
  classRef: rust
  config:
    image: ghcr.io/labring-actions/devbox/rust-1.81.0:50366f
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: rust 1.81.0
  version: "1.81.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: rust
spec:
  title: "rust"
  kind: Language
  description: rust
