name: 'Docker Registry Login'
description: 'Login to Docker registries (ghcr.io and Aliyun ACR)'
inputs:
  aliyun_enabled:
    description: 'Whether to enable Aliyun ACR login'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Login to ghcr.io
      shell: bash
      run: |
        printf '%s' "${{ secrets.GITHUB_TOKEN }}" > /tmp/ghcr_token
        chmod 600 /tmp/ghcr_token
        docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin < /tmp/ghcr_token
        rm -f /tmp/ghcr_token
    - name: Login to Aliyun ACR
      if: inputs.aliyun_enabled == 'true'
      shell: bash
      run: |
        printf '%s' "${{ secrets.ALIYUN_PASSWORD }}" > /tmp/aliyun_token
        chmod 600 /tmp/aliyun_token
        docker login "${{ secrets.ALIYUN_REGISTRY }}" -u "${{ secrets.ALIYUN_USERNAME }}" --password-stdin < /tmp/aliyun_token
        rm -f /tmp/aliyun_token
