name: 'Docker Registry Login'
description: 'Login to Docker registries (ghcr.io and Aliyun ACR)'
inputs:
  github_token:
    description: 'GitHub Token for ghcr.io login'
    required: true
  aliyun_credentials:
    description: 'JSON object containing Aliyun ACR credentials { "registry": string, "username": string, "password": string }'
    required: false
    default: '{}'
runs:
  using: 'composite'
  steps:
    - name: Login to ghcr.io
      shell: bash
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
    - name: Login to Aliyun ACR
      shell: bash
      if: inputs.aliyun_credentials != '{}' && inputs.aliyun_credentials != '' && inputs.aliyun_credentials != 'null'
      run: |
        registry=$(echo "${{ inputs.aliyun_credentials }}" | jq -r '.registry')
        username=$(echo "${{ inputs.aliyun_credentials }}" | jq -r '.username')
        password=$(echo "${{ inputs.aliyun_credentials }}" | jq -r '.password')
        if [ -n "$registry" ] && [ -n "$username" ] && [ -n "$password" ]; then
          echo "$password" | docker login "$registry" -u "$username" --password-stdin
        else
          echo "Error: Incomplete Aliyun credentials provided"
          exit 1
        fi
