name: 'Docker Registry Login'
description: 'Login to Docker registries (ghcr.io and Aliyun ACR)'
inputs:
  aliyun_enabled:
    description: 'Whether to enable Aliyun ACR login'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub Token for ghcr.io login'
    required: true
  aliyun_username:
    description: 'Username for Aliyun ACR login'
    required: false
  aliyun_password:
    description: 'Password for Aliyun ACR login'
    required: false
  aliyun_registry:
    description: 'Aliyun ACR registry URL'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Login to ghcr.io
      shell: bash
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
    - name: Login to Aliyun ACR
      if: inputs.aliyun_enabled == 'true'
      shell: bash
      run: echo "${{ inputs.aliyun_password }}" | docker login "${{ inputs.aliyun_registry }}" -u "${{ inputs.aliyun_username }}" --password-stdin
