name: 'Setup Docker Build Environment'
description: 'Setup Docker buildx and QEMU for multi-platform builds'
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
