#!/usr/bin/env bash

EXIT_CODE=$1

if [ "$EXIT_CODE" = "101" ]; then
    echo "code-server is disabled by environment. Preventing s6 restart."
    exit 125
fi

if [ "$EXIT_CODE" = "111" ]; then
    echo "code-server stopped because required files were not installed correctly. Preventing s6 restart."
    exit 125
fi

echo "code-server exited with code $EXIT_CODE, allowing s6 to restart it."
exit 1
