name: 'Build and Push Docker Images'
description: 'Build and push Docker images to multiple registries'
inputs:
  dockerfile:
    description: 'Dockerfile path'
    required: true
  ghcr_image_name:
    description: 'ghcr.io image name'
    required: true
  acr_image_name:
    description: 'Aliyun ACR image name'
    required: false
    default: ''
  aliyun_credentials:
    description: 'JSON object containing Aliyun ACR credentials { "registry": string, "username": string, "password": string }'
    required: false
    default: '{}'
runs:
  using: 'composite'
  steps:
    - name: Build and push to ghcr.io
      shell: bash
      run: |
        echo "Building and pushing to ghcr.io: ${{ inputs.ghcr_image_name }}"
        docker buildx build --push \
          --file "${{ inputs.dockerfile }}" \
          --platform linux/amd64 \
          --tag "${{ inputs.ghcr_image_name }}" \
          .
    - name: Build and push to Aliyun ACR
      shell: bash
      run: |
        # Check if Aliyun credentials are provided
        aliyun_credentials='${{ inputs.aliyun_credentials }}'
        if [ "$aliyun_credentials" != "{}" ] && [ "$aliyun_credentials" != "" ] && [ "$aliyun_credentials" != "null" ] && [ "${{ inputs.acr_image_name }}" != "" ]; then
          registry=$(echo "$aliyun_credentials" | jq -r '.registry')
          if [ -n "$registry" ] && [ "$registry" != "null" ]; then
            echo "Building and pushing to Aliyun ACR: ${{ inputs.acr_image_name }}"
            docker buildx build --push \
              --file "${{ inputs.dockerfile }}" \
              --platform linux/amd64 \
              --tag "${{ inputs.acr_image_name }}" \
              .
          fi
        fi
